# Grid size N x N
N1: 100

# Intrinsic proliferation rate (initial per-cell R)
R: 1.048

# Initial % occupancy (0-100)
m: 10

# Base mis-segregation rate per division
MSR: 0.003 # 0.3-1% per chromesome per motosis ###https://bionumbers.hms.harvard.edu/bionumber.aspx?id=105284&ver=7&trm=Rate+of+missegregation+of+a+chromosome++tumor+&org=

# Environmental MSR modulation factor in [-1, 1]
alpha: 0.5

# Baseline death probability per hour
Db: 0.001

# Ploidy-related growth factor beta in (0,1], effective hypoxia load gamma = beta*P
beta: 0.21

# Probability to die-by-division when space is full (if cell is due to divide)
Dv: 0.9

# Environmental oxygen supply level in [0,1] (used by oxygen field)
#Coxy: [0,0.1,1,10,20.5]
Coxy: [0,0.1,20.5]


# Initial WGD proportion at initialization (0-1)
WGDp: 0

# Per-division probability of WGD when there is space
WGDr: [0,0.01,0.1,0.2]

# Karyotype file path; must contain numeric column 'K'
#KaryoPath: "/Users/4482173/Documents/GitHub/ABM_Ploidy/ReqiuredData/karyotypes.csv"

#Maximum waiting time to death.
Dtime: 96

#Maximum simulation times.
SimsPerCoxy: 1

#Maximum chrom number
PloidyMax: 10

#QuiescentDeathHours
QuiescentDeathHours: 72

O2UseBoundary: true            # edge on/off
O2BoundaryMode: dirichlet_edges  # 'dirichlet_edges' 或 'neumann'
#O2BoundaryValue: 1.0           # edge o2（0~1）
O2DiffRate: 0.18                # difusion coef
O2SupplyRate: 0.01            #
O2Consume: 0.01                # cell cost
O2JacobiIters: 3
O2VesselSoftSupply: true

VesselDiameter: 10

# Output directory for all simulation files
OutDir: "/Volumes/Protable Disk/ABM_ploidy"
